"""Time-dependent dynamic spin-up model for foldable propeller (V1 skeleton)."""

from .aero import quasi_steady_aero, reference_propeller_thrust_n
from .aero_effectiveness import (
    FOLDED_MIN_AERO_EFFECTIVENESS,
    aero_effectiveness_from_progress,
    deployment_progress_from_theta,
)
from .calibration import (
    IDEAL_GEOMETRY_RATIO_NOTE,
    SPINUP_SUMMARY_CSV_COLUMNS,
    PRETEST_REFERENCE_FRACTION,
    PROJECT_TARGET_FRACTION,
    FOLDABLE_OPEN_DIAMETER_M,
    CHECKPOINT_RPM,
    FOLDABLE_STOWED_ENVELOPE_DIAMETER_M,
    SpinUpCheckpointSummary,
    CheckpointValidationSummary,
    spinup_checkpoint_summary,
    checkpoint_validation_summary,
    write_spinup_summary_csv,
)
from .dynamics_frame import (
    concept_frame_from_dynamic,
    parse_root_tip_ratios,
    rotor_azimuth_rad,
    visual_state_from_dynamic,
)
from .figures import SPINUP_REPORT_FIGURE_NOTE, plot_spinup_summary
from .frames import (
    SINGLE_ARM_CONCEPT_NOTE,
    export_spinup_frames,
    spinup_frames_dir,
)
from .hinge import initial_hinge_state, integrate_hinge_step, quasi_static_theta_deg
from .hinge_dynamics import HingeDynamicsMode, HingeState
from .hinge_moment_geometry import (
    CENT_MOMENT_MODELS,
    CentMomentModel,
    centrifugal_moment_nm_for_model,
    initial_theta_deg,
)
from .hinge_moments import HingeMomentComponents, compute_hinge_moments
from ..kinematics import classify_physics_hinge_state
from .integrator import euler_step
from .motor import algebraic_motor_current, applied_voltage_v, motor_torque_nm
from .physics_thrust_split_diagnostic import (
    THRUST_SPLIT_COMPARISON_COLUMNS,
    ThrustSplitComparisonRow,
    run_thrust_split_model_comparison,
    write_thrust_split_model_comparison_csv,
)
from .physics_calibrated_thrust_split_diagnostic import (
    CALIBRATED_THRUST_SPLIT_DIAGNOSTIC_COLUMNS,
    run_calibrated_thrust_split_diagnostic,
    write_calibrated_thrust_split_diagnostic_csv,
)
from .cfd_preparation import (
    CFD_GEOMETRY_PARAMETERS_V2_COLUMNS,
    CFD_OPERATING_POINTS_V2_COLUMNS,
    CFD_PREP_OUTPUT_DIR,
    CFD_READINESS_AUDIT_V2_COLUMNS,
    CFD_STATUS_NOTE,
    run_cfd_preparation_v2,
    write_cfd_geometry_parameters_v2_csv,
    write_cfd_operating_points_v2_csv,
    write_cfd_readiness_audit_v2_csv,
)
from .motor_coupled_performance import (
    MOTOR_COUPLED_7100RPM_CHECKPOINT_V2_COLUMNS,
    MOTOR_COUPLED_7100RPM_INTERPOLATED_V2_COLUMNS,
    MOTOR_COUPLED_CONSISTENCY_AUDIT_V2_COLUMNS,
    MOTOR_COUPLED_FOLDABLE_PERFORMANCE_V2_COLUMNS,
    MOTOR_COUPLED_REFERENCE_CONSISTENCY_V2_COLUMNS,
    MOTOR_COUPLING_LEVEL,
    InterpolatedMotorScalars,
    MotorCoupled7100CheckpointRow,
    MotorCoupled7100InterpolatedRow,
    MotorCoupledConsistencyAuditRow,
    MotorCoupledPerformanceRow,
    MotorCoupledReferenceConsistencyRow,
    compute_foldable_aero_torque,
    interpolate_motor_scalars_at_target_rpm,
    reference_25cm_at_rpm_n,
    run_motor_coupled_7100rpm_checkpoint_v2,
    run_motor_coupled_7100rpm_interpolated_v2,
    run_motor_coupled_consistency_audit_v2,
    run_motor_coupled_foldable_performance_v2,
    run_motor_coupled_reference_consistency_v2,
    write_motor_coupled_7100rpm_checkpoint_v2_csv,
    write_motor_coupled_7100rpm_interpolated_v2_csv,
    write_motor_coupled_consistency_audit_v2_csv,
    write_motor_coupled_foldable_performance_v2_csv,
    write_motor_coupled_reference_consistency_v2_csv,
)
from .physics_foldable_design_decision import (
    FOLDABLE_CANDIDATE_RANKING_V2_COLUMNS,
    FOLDABLE_DESIGN_DECISION_MATRIX_V2_COLUMNS,
    FoldableCandidateRankingRow,
    FoldableDesignDecisionRow,
    run_foldable_candidate_ranking_v2,
    run_foldable_design_decision_matrix_v2,
    write_foldable_candidate_ranking_v2_csv,
    write_foldable_design_decision_matrix_v2_csv,
)
from .physics_foldable_performance import (
    FOLDABLE_PERFORMANCE_SUMMARY_V2_COLUMNS,
    FoldableEvaluationContext,
    FoldablePerformanceSummaryRow,
    FoldableThrustEvaluation,
    evaluate_foldable_thrust_at_state,
    resolve_foldable_evaluation_context,
    run_foldable_performance_summary_v2,
    write_foldable_performance_summary_v2_csv,
)
from .physics_deployment_sweep import (
    DEPLOYMENT_BIAS_STIFFNESS_SWEEP_COLUMNS,
    DeploymentSweepRow,
    run_deployment_bias_stiffness_sweep,
    run_open_latch_diagnostic_cases,
    write_deployment_bias_stiffness_sweep_csv,
)
from .physics_tip_thrust_diagnostic import (
    TIP_THRUST_ACTIVATION_COLUMNS,
    TipThrustActivationRow,
    run_tip_thrust_activation_diagnostic,
    run_tip_thrust_latch_comparison,
    write_tip_thrust_activation_csv,
)
from .physics_moment_geometry_diagnostic import (
    MOMENT_GEOMETRY_DIAGNOSTIC_COLUMNS,
    MomentGeometryDiagnosticRow,
    run_moment_geometry_diagnostic_cases,
    write_moment_geometry_diagnostic_csv,
)
from .physics_stability import (
    DIAGNOSTIC_SWEEP_COLUMNS,
    STABILITY_REPORT_COLUMNS,
    StabilityMetrics,
    analyze_physics_stability,
    quasi_static_equilibrium_theta_deg,
    run_dt_sensitivity_cases,
    run_hinge_parameter_diagnostic_sweep,
    scaled_hinge_config,
    write_diagnostic_sweep_csv,
    write_stability_report,
)
from .physics_figures import plot_physics_debug_figures
from .physics_simulation import run_prescribed_rpm_physics
from .physics_state import PHYSICS_DEBUG_CSV_COLUMNS, PhysicsState, write_physics_csv
from .prescribed_rpm import PrescribedRpmConfig
from .thrust_split_calibration import (
    DEFAULT_CALIBRATION_REFERENCE_CASE_ID,
    TIP_DELTA_CALIBRATION_PRESETS,
    CalibratedThrustSplitDiagnostics,
    FixedCalibrationFactors,
    TipDeltaCalibrationPreset,
    compute_calibrated_thrust_split_diagnostics,
    compute_fixed_calibration_factors,
    tip_delta_efficiency_factor_for_preset,
)
from .split_thrust import (
    MODE_NOTES,
    THRUST_SPLIT_MODES,
    SplitThrustResult,
    ThrustSplitMode,
    TipThrustBreakdown,
    compute_split_thrust,
    compute_tip_thrust_breakdown,
)
from .rotor import default_rotor_inertia_kgm2, rotor_acceleration_rad_s2
from .simulation import (
    MODEL_ASSUMPTIONS,
    SpinUpConfig,
    build_throttle_schedule,
    default_throttle_schedule,
    run_spinup_simulation,
    write_spinup_csv,
)
from .state import SPINUP_CSV_COLUMNS, DynamicState
from .throttle import ThrottleProfileName, throttle_at_time

__all__ = [
    "FOLDED_MIN_AERO_EFFECTIVENESS",
    "DEPLOYMENT_BIAS_STIFFNESS_SWEEP_COLUMNS",
    "DIAGNOSTIC_SWEEP_COLUMNS",
    "DeploymentSweepRow",
    "TIP_THRUST_ACTIVATION_COLUMNS",
    "TipThrustActivationRow",
    "TipThrustBreakdown",
    "HingeDynamicsMode",
    "HingeMomentComponents",
    "HingeState",
    "CENT_MOMENT_MODELS",
    "CALIBRATED_THRUST_SPLIT_DIAGNOSTIC_COLUMNS",
    "DEFAULT_CALIBRATION_REFERENCE_CASE_ID",
    "FOLDABLE_CANDIDATE_RANKING_V2_COLUMNS",
    "FOLDABLE_DESIGN_DECISION_MATRIX_V2_COLUMNS",
    "FOLDABLE_PERFORMANCE_SUMMARY_V2_COLUMNS",
    "FoldableCandidateRankingRow",
    "FoldableDesignDecisionRow",
    "FixedCalibrationFactors",
    "FoldableEvaluationContext",
    "FoldablePerformanceSummaryRow",
    "FoldableThrustEvaluation",
    "CalibratedThrustSplitDiagnostics",
    "TIP_DELTA_CALIBRATION_PRESETS",
    "TipDeltaCalibrationPreset",
    "CentMomentModel",
    "CFD_GEOMETRY_PARAMETERS_V2_COLUMNS",
    "CFD_OPERATING_POINTS_V2_COLUMNS",
    "CFD_PREP_OUTPUT_DIR",
    "CFD_READINESS_AUDIT_V2_COLUMNS",
    "CFD_STATUS_NOTE",
    "MODE_NOTES",
    "THRUST_SPLIT_MODES",
    "THRUST_SPLIT_COMPARISON_COLUMNS",
    "ThrustSplitComparisonRow",
    "ThrustSplitMode",
    "MOTOR_COUPLED_7100RPM_CHECKPOINT_V2_COLUMNS",
    "MOTOR_COUPLED_7100RPM_INTERPOLATED_V2_COLUMNS",
    "MOTOR_COUPLED_FOLDABLE_PERFORMANCE_V2_COLUMNS",
    "MOTOR_COUPLED_CONSISTENCY_AUDIT_V2_COLUMNS",
    "MOTOR_COUPLED_REFERENCE_CONSISTENCY_V2_COLUMNS",
    "MOTOR_COUPLING_LEVEL",
    "MotorCoupled7100CheckpointRow",
    "MotorCoupled7100InterpolatedRow",
    "MotorCoupledPerformanceRow",
    "MotorCoupledReferenceConsistencyRow",
    "InterpolatedMotorScalars",
    "MomentGeometryDiagnosticRow",
    "IDEAL_GEOMETRY_RATIO_NOTE",
    "MODEL_ASSUMPTIONS",
    "PHYSICS_DEBUG_CSV_COLUMNS",
    "PhysicsState",
    "PrescribedRpmConfig",
    "SINGLE_ARM_CONCEPT_NOTE",
    "SPINUP_CSV_COLUMNS",
    "SPINUP_REPORT_FIGURE_NOTE",
    "SPINUP_SUMMARY_CSV_COLUMNS",
    "STABILITY_REPORT_COLUMNS",
    "SplitThrustResult",
    "StabilityMetrics",
    "PRETEST_REFERENCE_FRACTION",
    "PROJECT_TARGET_FRACTION",
    "FOLDABLE_OPEN_DIAMETER_M",
    "CHECKPOINT_RPM",
    "FOLDABLE_STOWED_ENVELOPE_DIAMETER_M",
    "DynamicState",
    "SpinUpCheckpointSummary",
    "SpinUpConfig",
    "ThrottleProfileName",
    "CheckpointValidationSummary",
    "aero_effectiveness_from_progress",
    "algebraic_motor_current",
    "analyze_physics_stability",
    "applied_voltage_v",
    "build_throttle_schedule",
    "centrifugal_moment_nm_for_model",
    "classify_physics_hinge_state",
    "compute_hinge_moments",
    "compute_fixed_calibration_factors",
    "compute_calibrated_thrust_split_diagnostics",
    "compute_split_thrust",
    "compute_tip_thrust_breakdown",
    "concept_frame_from_dynamic",
    "default_rotor_inertia_kgm2",
    "default_throttle_schedule",
    "deployment_progress_from_theta",
    "euler_step",
    "evaluate_foldable_thrust_at_state",
    "export_spinup_frames",
    "compute_foldable_aero_torque",
    "reference_25cm_at_rpm_n",
    "initial_theta_deg",
    "integrate_hinge_step",
    "motor_torque_nm",
    "parse_root_tip_ratios",
    "plot_physics_debug_figures",
    "plot_spinup_summary",
    "quasi_static_equilibrium_theta_deg",
    "quasi_static_theta_deg",
    "quasi_steady_aero",
    "reference_propeller_thrust_n",
    "resolve_foldable_evaluation_context",
    "rotor_acceleration_rad_s2",
    "rotor_azimuth_rad",
    "run_foldable_candidate_ranking_v2",
    "run_foldable_design_decision_matrix_v2",
    "run_foldable_performance_summary_v2",
    "run_calibrated_thrust_split_diagnostic",
    "run_cfd_preparation_v2",
    "run_deployment_bias_stiffness_sweep",
    "run_dt_sensitivity_cases",
    "run_open_latch_diagnostic_cases",
    "run_hinge_parameter_diagnostic_sweep",
    "run_motor_coupled_7100rpm_checkpoint_v2",
    "run_motor_coupled_7100rpm_interpolated_v2",
    "run_motor_coupled_foldable_performance_v2",
    "run_motor_coupled_reference_consistency_v2",
    "interpolate_motor_scalars_at_target_rpm",
    "run_motor_coupled_consistency_audit_v2",
    "run_moment_geometry_diagnostic_cases",
    "run_tip_thrust_activation_diagnostic",
    "run_thrust_split_model_comparison",
    "run_tip_thrust_latch_comparison",
    "run_prescribed_rpm_physics",
    "run_spinup_simulation",
    "scaled_hinge_config",
    "spinup_checkpoint_summary",
    "spinup_frames_dir",
    "tip_delta_efficiency_factor_for_preset",
    "throttle_at_time",
    "checkpoint_validation_summary",
    "visual_state_from_dynamic",
    "write_foldable_candidate_ranking_v2_csv",
    "write_foldable_design_decision_matrix_v2_csv",
    "write_foldable_performance_summary_v2_csv",
    "write_calibrated_thrust_split_diagnostic_csv",
    "write_cfd_geometry_parameters_v2_csv",
    "write_cfd_operating_points_v2_csv",
    "write_cfd_readiness_audit_v2_csv",
    "write_deployment_bias_stiffness_sweep_csv",
    "write_diagnostic_sweep_csv",
    "write_tip_thrust_activation_csv",
    "write_thrust_split_model_comparison_csv",
    "write_motor_coupled_7100rpm_checkpoint_v2_csv",
    "write_motor_coupled_7100rpm_interpolated_v2_csv",
    "write_motor_coupled_foldable_performance_v2_csv",
    "write_motor_coupled_reference_consistency_v2_csv",
    "write_motor_coupled_consistency_audit_v2_csv",
    "write_moment_geometry_diagnostic_csv",
    "write_physics_csv",
    "write_spinup_csv",
    "write_spinup_summary_csv",
    "write_stability_report",
]
